### ISSUE TITLE
CSV Import for further Data

### ISSUE THREAD

**Issue by mr2017x** [numero2/contao-storelocator#31]
Good Day and thanks for the pretty nice extension. i am asking myself if it is possible to import more than the given csv-string name, email, url, telefon, fax, strasse, plz, ort, ländercode (ISO 3166-2). 

For example: it would be perfect if the csv import would also handle description and opening times.

Thank you

**Comment by bennyborn** [comment]
These fields are left out on purpose.
The problem with these data is the format and the capabilities of the CSV format itself.

A description contains HTML-Code which has attributes that are enclosed in double quotes which is also used to mark the actual cell data in a CSV. You'd need to correctly escape all double quotes in a description otherwise you'd risk ending up with garbled data.

For the opening times: We have 3 fields for each day - the day itself, opening time, closing time.
The only really usable way (for a normal end user, not a developer) would be to add 3 columns for each day. Given a 5 to 7 day week we'd end up with 21 additional columns - way too much.

So at this point I don't really see a practical way to include these two fields in a simple CSV import.

**Comment by mr2017x** [comment]
Hi Benny,

thank you. 
regarding your opening time concerns i am totally with you
regarding your concerns to Description i would appreciate an easy way - no html, and special chars should be fine by utf8?
