### ISSUE TITLE
Respect slug settings from Contao

### ISSUE THREAD

**Issue by stefansl** [numero2/contao-storelocator#45]
Generating the alias doesn't respect the slug settings in your site structure:
https://github.com/numero2/contao-storelocator/blob/2ba308dad9f85b71b74e15ac1bffd27060803163/src/Resources/contao/library/StoreLocator/DCAHelper/Stores.php#L92

This is the way to go:
https://github.com/numero2/contao-proper-filenames/pull/4

**Comment by bennyborn** [comment]
Actually https://github.com/numero2/contao-proper-filenames does not respect the settings from the site structure either because in both cases we have no connection to a specific root page. But I agree that we should add some kind of setting to configure the behaviour and eventually use the slug generator.

**Comment by stefansl** [comment]
Ahhh, you're right. As long the alias is managed via DCA it's only possible to use own settings from tl_settings or tl_storelocator_categories.
